### ISSUE TITLE
Griddy could have the ability to 'star' or 'fave' talks

### ISSUE THREAD

**Issue by tommorris** [geeksoflondon/grid4rails#127] opened 2011-10-31 14:03 UTC
This has been a recurring topic of conversation during and after BCL9, so I felt we should start a discussion on this.

There are a variety of possible uses for this: marking talks you want to go to, and giving props for talks one has liked. The former is very useful, and also means we can work out scheduling stuff better. That is, if we've got a talk with 50 stars in a room for 40 people and another talk with only 5 stars in a room for 100 people, it would make sense to swap the two (obviously, notifying that person too would be helpful - perhaps a reason to integrate with Twitter or ask for the person to provide an e-mail address or mobile number for notifications).

**Comment by martian-a** [comment] 2011-10-31 16:30
Duplicate of https://github.com/geeksoflondon/grid4rails/issues/119

**Closed as completed by martian-a** 2011-10-31 16:30 UTC
Labels: 3 - could have

**Comment by markstickley** [comment] 2011-10-31 18:29
The session flagging idea is an excellent one and would be very useful for marking which session(s) you are interested in and which you went to. 

I'm not too sure any rating system beyond how many people actually attended the session would be beneficial as there is potential for the speaker to get upset about few or poor ratings. 

Of course the signing in thing wouldn't just be for notifications as there would have to be the concept of a user to tie the flags to whether they were identifiable or anonymous based on a session id or whatever. Really though I think it would be more beneficial to have identifiable users than to provide this functionality to the few who would object to having to sign in. 

I'm not sure forcing the user to sign in with twitter is that good a move, however. There should probably be an option of a quick sign in with twitter or a full native registration. I have a little experience with this kind of user journey having working on the BBC's single sign on system, and am happy to work out flows and edge cases :)

M

**Comment by martian-a** [comment] 2011-11-04 11:24
Favourites and a personal schedule already have individual tickets and I've just created one for user authentication.  It would help to keep things simple if we could keep the discussion on each issue separate, please:

Favourites: https://github.com/geeksoflondon/grid4rails/issues/119
Personal Schedule: https://github.com/geeksoflondon/grid4rails/issues/118
User Authentication: https://github.com/geeksoflondon/grid4rails/issues/128
